### ISSUE TITLE
ABNF syntax highlighting not properly enabled?

### ISSUE THREAD

**Issue by tidoust** [w3c/respec-hljs#15]
The [documentation](https://github.com/w3c/respec/wiki/pre-and-code-elements) currently asserts that code highlighting is supported for ABNF but as far as I can tell this is not the case.

I see in [respec-hljs](https://github.com/w3c/respec-hljs/blob/hljs/src/respec-highlight.js) that `abnf` is mentioned but there does not seem to be a corresponding call to `registerLanguage`. Aren't the following lines missing?

```js
import abnf from "highlight.js/lib/languages/abnf";
highlight.registerLanguage("abnf", abnf);
```

Or did you drop ABNF support on purpose?

**Comment by marcoscaceres** [comment]
Can't remember why I dropped it... we can add it again :)

**Comment by tidoust** [comment]
That would be great! I have a bit of ABNF in a draft spec for which I'd love to enable syntax highlighting.

**Comment by marcoscaceres** [comment]
Sounds good, but be prepared that last we had Syntax highlighting for ABNF it was a bit underwhelming. Might have gotten better 🤞
